# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 10
language: 'en-uk'

# Website info
baseurl: /exteryo-safety-blog/
url: https://Exteryo-Dev-Team.github.io
title: Exteryo Safety Blog
description: Engineering and safety insights from the Exteryo team.

# Permalinks
permalink: /:title/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
