# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 6
language: 'en-uk'
words_per_minute: 200

# Remote Theme
remote_theme: jekyller/jasper2

# Website info
baseurl: /exteryo-safety-blog
url: https://Exteryo-Dev-Team.github.io
title: Exteryo Safety Blog
description: Engineering and safety insights from the Exteryo team.
cover: assets/images/blog-cover.png
logo: assets/images/blog-icon.png
# logo_dark: assets/images/favicon.png
# favicon: assets/images/favicon.png

# Social info
navigation: True
subscribers: True
twitter: ExteryoDev

# Disqus
disqus: False

# Google Analytics
# google_analytics: UA-XXXXX-X

# Permalinks
permalink: /:title

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
